"""Synthetic FactSet/PitchBook-style world generator for two-stage Hawkes calibration.

Two ground-truth regimes:

* Regime A (well-specified): the world is generated by the exact two-stage model the
  package fits — weekly sector count GLM with lagged positive excitation, plus a
  risk-set softmax ranker with negative cooldown.  Use it for parameter-recovery
  sanity checks under observation noise.

* Regime B (misspecified): the world is a daily firm-level block Hawkes process with
  self-inhibition and sector peer excitation (log-link, latent firm quality).  The
  two-stage weekly model is *not* the true DGP.  Use it as a robustness stress test.

Both regimes are materialised through the same observation layer into PitchBook-style
tables (deals / companies / investors) plus a FactSet-style long macro feed
(FFUNDT, FFUND, CPI_RAW, CPI_YOY, RUNEMP) with publication lags, and re-loaded into
fitter-ready arrays by :mod:`synthetic.loaders`.
"""

from .firms import generate_universe
from .loaders import LoadedDataset, load_dataset
from .macro import MACRO_SERIES, generate_macro, weekly_macro_matrix
from .observe import build_pitchbook_tables
from .regime_a import simulate_regime_a
from .regime_b import simulate_regime_b

__all__ = [
    "generate_macro",
    "weekly_macro_matrix",
    "MACRO_SERIES",
    "generate_universe",
    "simulate_regime_a",
    "simulate_regime_b",
    "build_pitchbook_tables",
    "load_dataset",
    "LoadedDataset",
]
